name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          
          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/smtp-relay-linux-amd64 cmd/smtp-relay/main.go
          
          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/smtp-relay-linux-arm64 cmd/smtp-relay/main.go
          
          # Build for macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/smtp-relay-darwin-amd64 cmd/smtp-relay/main.go
          
          # Build for macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o dist/smtp-relay-darwin-arm64 cmd/smtp-relay/main.go
          
          # Build for Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/smtp-relay-windows-amd64.exe cmd/smtp-relay/main.go

      - name: List built files
        run: ls -la dist/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
